# Generated by Django 5.0.1 on 2024-01-31 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_BIC', models.CharField(max_length=255)),
                ('sender_name', models.CharField(max_length=50)),
                ('receiver_BIC', models.CharField(max_length=255)),
                ('receiver_name', models.CharField(max_length=50)),
                ('request_description', models.CharField(max_length=1050)),
                ('status', models.CharField(blank=True, choices=[('pending', 'pending'), ('active', 'active'), ('rejected', 'rejected')], max_length=32, null=True)),
                ('created_date', models.DateTimeField(max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
